### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by adam-tokarski** [AM0k84/PORTFOLIO_website#12]
As soon as possible please remove [secret key](https://github.com/AM0k84/PORTFOLIO_website/blob/develop/portfolio/settings.py#L22) and [email host password](https://github.com/AM0k84/PORTFOLIO_website/blob/develop/portfolio/settings.py#L132) from repo. Instead of that think about using some variables from env file, or similar, which is NOT added into repository. 

Please change these values, especially email password, to avoid that someone will use that to some evil things. In case that these are not real values, please change them anyway, as if someone is going to review your code (I saw your post in linkedin that you're open to job offers), he will notice that anyway, and - trust me - it will be assessed negatively.

**Comment by AM0k84** [comment]
Thank you for reporting this issue. I just have fixed it. In my next projects I'm, using .env where I keep all sensitive data.

**Comment by adam-tokarski** [comment]
That was quick, thanks.
And please remember to change the password in email host. GH is regular scanned for credentials, so I bet that this one is in some passwords db.
